# Generated by Django 3.2.7 on 2024-03-14 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240313_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tin', models.CharField(default='', max_length=127, verbose_name='ИНН')),
                ('container_number', models.CharField(default='', max_length=127, verbose_name='Номер контейнера')),
                ('description', models.TextField(default='', verbose_name='Описание магазина')),
                ('paid_status', models.BooleanField(default=False, verbose_name='Статус оплаты подписки')),
                ('paid_date', models.DateField(default='', verbose_name='Дата оплаты')),
                ('lat', models.FloatField(default=0.0, verbose_name='Широта')),
                ('long', models.FloatField(default=0.0, verbose_name='Долгота')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_user', to=settings.AUTH_USER_MODEL, verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Продавец',
                'verbose_name_plural': 'Продавцы',
            },
        ),
    ]
