# Generated by Django 3.2.7 on 2024-03-28 12:55

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20240327_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleruser',
            name='main_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=100, scale=0.5, size=[1440, 2560], upload_to='users/images_main', verbose_name='Фото главная'),
        ),
        migrations.AddField(
            model_name='selleruser',
            name='mini_description',
            field=models.CharField(default='', max_length=150, verbose_name='Описание на главной'),
        ),
        migrations.AddField(
            model_name='selleruser',
            name='shop_name',
            field=models.CharField(default='', max_length=100, verbose_name='Название магазина'),
        ),
    ]
