# Generated by Django 3.2.7 on 2024-03-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20240328_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleruser',
            name='followers',
            field=models.IntegerField(default=0, verbose_name='Количество подписчиков'),
        ),
        migrations.AddField(
            model_name='selleruser',
            name='product',
            field=models.IntegerField(default=0, verbose_name='Количество товаров'),
        ),
    ]
