# Generated by Django 3.2.7 on 2024-04-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20240328_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='code_activation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='code_time',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен ли?'),
        ),
    ]
