# Generated by Django 3.2.7 on 2024-04-11 13:16

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selleruser',
            name='background_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=100, scale=0.8, size=[1440, 2560], upload_to='users/images_back', verbose_name='Фото заднее'),
        ),
        migrations.AlterField(
            model_name='selleruser',
            name='insta_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=100, scale=0.8, size=[1440, 2560], upload_to='users/images_back', verbose_name='Фото инста'),
        ),
        migrations.AlterField(
            model_name='selleruser',
            name='main_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=100, scale=0.8, size=[1440, 2560], upload_to='users/images_main', verbose_name='Фото главная'),
        ),
    ]
