# Generated by Django 3.2.7 on 2024-05-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_selleruser_telegram_link'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='selleruser',
            index=models.Index(fields=['shop_name'], name='users_selle_shop_na_7f462a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='users_user_phone_n_7fe504_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_user_role_36d76d_idx'),
        ),
    ]
