# Generated by Django 3.2.7 on 2024-04-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Строковое значение имени пользователя', max_length=127, verbose_name='Имя пользователя')),
                ('phone_number', models.CharField(help_text='Строковое значение номера телефона', max_length=20, verbose_name='Номер телефона')),
                ('instagram_link', models.CharField(blank=True, help_text='Строковое значение ссылки на инстаграм', max_length=127, null=True, verbose_name='Ссылка на Instagram')),
                ('application_text', models.TextField(help_text='Тексовое значения заявки', verbose_name='Текст заявки')),
                ('created_at', models.DateField(auto_now_add=True, help_text='Дата создания заявки формируется автомотически', verbose_name='Дата создания заявки')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FooterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Контактный номер телефона в футере', max_length=25, unique=True, verbose_name='Номер телефона')),
                ('instagram_link', models.CharField(help_text='Ссылка на наш инстаграм в строковом значении', max_length=127, unique=True, verbose_name='Ссылка на наш инстаграм')),
            ],
        ),
    ]
